spring:
  application:
    名字: adg-rule
  profiles:
    已激活: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  rule:
    #远程规则
    remote:
      # FutaGuard/LowTechFilter
      - 'https://filter.futa.gg/filter.txt' 
      - 'https://filter.futa.gg/hide_farm_from_search.txt'
      - 'https://filter.futa.gg/removeparam.txt'
      - 'https://filter.futa.gg/TW165.txt' #TW165
      # QuarkList
      - 'https://raw.githubusercontent.com/francis-zhao/quarklist/master/dist/quarklist.txt'
      # Crystal-RainSlide/AdditionalFiltersCN
      - 'https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/CN.txt'
      - 'https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/Intl.txt'
      - 'https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/Game.txt'
      - 'https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/CN/NoWeWontChat.txt'
      - 'https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/CN/fix.txt'
      # jiayiming/jCleanList
      - 'https://raw.githubusercontent.com/jiayiming/jCleanList/master/jCleanList_all.txt'
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
      #- 'mylist.txt'
  output:
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt:    #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      adgh.txt:
        - DOMAIN
        - REGEX
#        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
