spring:
  application:
    名字: adg-rule
  profiles:
    已激活: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  rule:
    #远程规则
    remote:
      # EasyList
      - 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_adservers.txt' #EasyList adservers
      - 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_allowlist.txt' #easylist - allowlist
      - 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_adservers_popup.txt' #EasyList adservers popup
      #- 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_general_block.txt' #EasyList general block
      #- 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_general_block_popup.txt' #EasyList general popup
      #- 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_general_hide.txt' #easylist_general_hide
      - 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_thirdparty.txt' #EasyList — third-party servers
      - 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_thirdparty_popup.txt' #easylist_thirdparty_popup
      #- 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_specific_block.txt' #easylist_specific_block
      #- 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_specific_block_popup.txt' #easylist_specific_block_popup
      #- 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_specific_hide.txt' #easylist_specific_hide
      - 'https://raw.githubusercontent.com/easylist/easylistchina/master/easylistchina.txt' #EasyList China
      - 'https://easylist-downloads.adblockplus.org/antiadblockfilters.txt' #Adblock Warning Removal List
      - 'https://raw.githubusercontent.com/easylist/antiadblockfilters/master/antiadblockfilters/antiadblock_english.txt' #easylist/antiadblockfilters
      # Fanboy
      - 'https://easylist.to/easylist/fanboy-social.txt'
      - 'https://secure.fanboy.co.nz/fanboy-annoyance.txt'
      - 'https://secure.fanboy.co.nz/fanboy-cookiemonster.txt'
      # AdGuard
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/adservers.txt' #AdGuard DNS BaseFilter
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/adservers_firstparty.txt' #AdGuard BaseFilter — first-party servers
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/content_blocker.txt' #BaseFilter content_blocker
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/allowlist.txt' #BaseFilter allowlist 
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/banner_sizes.txt' #banner sizes
      #- 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/general_elemhide.txt' #general_elemhide
      #- 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/general_extensions.txt' #general_extensions
      #- 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/general_url.txt' #general_url
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/MobileFilter/sections/allowlist_web.txt' #MobileFilter allowlist_web
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/ChineseFilter/sections/specific.txt' #Chinese specific
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/ChineseFilter/sections/adservers_firstparty.txt' #AdGuard Chinese filter — first-party servers
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/ChineseFilter/sections/antiadblock.txt'#ChineseFilter antiadblock
      #- 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/ChineseFilter/sections/general_elemhide.txt' #general_elemhide
      #- 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/ChineseFilter/sections/general_extensions.txt'#general_extensions
      #- 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/ChineseFilter/sections/general_url.txt' #general_url
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/ChineseFilter/sections/replace.txt' #replace
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/ChineseFilter/sections/specific.txt' #specific
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/ChineseFilter/sections/allowlist.txt' #ChineseFilter allowlist
      - 'https://filters.adtidy.org/extension/ublock/filters/3_optimized.txt' #AdGuard Tracking Protection filter 
      # cjx82630/cjxlist
      - 'https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-ublock.txt'
      - 'https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt'
      - 'https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt'
      # adgk
      - 'https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt'
      - 'https://raw.githubusercontent.com/banbendalao/ADgk/master/kill-baidu-ad.txt'
      # xinggsf/Adblock-Plus-Rule
      - 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt'
      - 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt'
      # TG-Twilight/AWAvenue-Ads-Rule
      - 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt'
      # FutaGuard/LowTechFilter
      # - 'https://filter.futa.gg/filter.txt' #影响知乎
      - 'https://filter.futa.gg/hide_farm_from_search.txt'
      - 'https://filter.futa.gg/removeparam.txt'
      - 'https://filter.futa.gg/TW165.txt' #TW165
      # 1Hosts
      - 'https://raw.githubusercontent.com/badmojr/1Hosts/master/Lite/adblock.txt'
      # QuarkList
      - 'https://raw.githubusercontent.com/francis-zhao/quarklist/master/dist/quarklist.txt'
      # Crystal-RainSlide/AdditionalFiltersCN
      - 'https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/CN.txt'
      - 'https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/Intl.txt'
      - 'https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/Game.txt'
      - 'https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/CN/NoWeWontChat.txt'
      - 'https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/CN/fix.txt'
      # damengzhu/banad
      - 'https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt'
      # jiayiming/jCleanList
      - 'https://raw.githubusercontent.com/jiayiming/jCleanList/master/jCleanList_all.txt'
      #  ABP anti-circumvention filter list
      - 'https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt'
      - 'https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/raw/master/chinese.txt?ref_type=heads'
      - 'https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/raw/master/english.txt?ref_type=heads'
      # DandelionSprout/adfilt ClearURLs for uBo
      - 'https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt'
      # Noyllopa/NoAppDownload
      - 'https://raw.githubusercontent.com/Noyllopa/NoAppDownload/master/NoAppDownload.txt'
      # Spam404
      - 'https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt' 
      # Cryptominers
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/cryptominers.txt' #AdGuard Cryptominers
      - 'https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt' #hoshsadiq/adblock-nocoin-list
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
      #- 'mylist.txt'
  output:
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt:    #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      adgh.txt:
        - DOMAIN
        - REGEX
#        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
