spring:
  application:
    名字: adg-rule
  profiles:
    已激活: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  rule:
    #远程规则
    remote:
      # EasyList
      - 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_adservers.txt' #EasyList adservers
      - 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_adservers_popup.txt' #EasyList adservers popup
      - 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_general_block.txt' #EasyList general block
      - 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_general_block_popup.txt' #EasyList general popup
      - 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_general_hide.txt' #easylist_general_hide
      - 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_thirdparty.txt' #EasyList — third-party servers
      - 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_thirdparty_popup.txt' #easylist_thirdparty_popup
      #- 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_specific_block.txt' #easylist_specific_block
      #- 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_specific_block_popup.txt' #easylist_specific_block_popup
      #- 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_specific_hide.txt' #easylist_specific_hide
      - 'https://raw.githubusercontent.com/easylist/easylistchina/master/easylistchina.txt' #EasyList China
      - 'https://easylist-downloads.adblockplus.org/antiadblockfilters.txt' #Adblock Warning Removal List
      # Fanboy
      - 'https://easylist.to/easylist/fanboy-social.txt'
      - 'https://secure.fanboy.co.nz/fanboy-annoyance.txt'
      - 'https://secure.fanboy.co.nz/fanboy-cookiemonster.txt'
      # cjx82630/cjxlist
      - 'https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-ublock.txt'
      - 'https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt'
      - 'https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt'
      # xinggsf/Adblock-Plus-Rule
      - 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt'
      - 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt'
      # FutaGuard/LowTechFilter
      - 'https://filter.futa.gg/filter.txt' 
      - 'https://filter.futa.gg/hide_farm_from_search.txt'
      - 'https://filter.futa.gg/removeparam.txt'
      - 'https://filter.futa.gg/TW165.txt' #TW165
      # 1Hosts
      - 'https://raw.githubusercontent.com/badmojr/1Hosts/master/Lite/adblock.txt'
      # QuarkList
      - 'https://raw.githubusercontent.com/francis-zhao/quarklist/master/dist/quarklist.txt'
      # Crystal-RainSlide/AdditionalFiltersCN
      - 'https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/CN.txt'
      - 'https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/Intl.txt'
      - 'https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/Game.txt'
      - 'https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/CN/NoWeWontChat.txt'
      - 'https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/CN/fix.txt'
      # jiayiming/jCleanList
      - 'https://raw.githubusercontent.com/jiayiming/jCleanList/master/jCleanList_all.txt'
      #  ABP anti-circumvention filter list
      - 'https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt'
      - 'https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/raw/master/chinese.txt?ref_type=heads'
      - 'https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/raw/master/english.txt?ref_type=heads'
      # Cryptominers
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/cryptominers.txt' #AdGuard Cryptominers
      - 'https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt' #hoshsadiq/adblock-nocoin-list
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
      #- 'mylist.txt'
  output:
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt:    #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      adgh.txt:
        - DOMAIN
        - REGEX
#        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
